---
title: "Lab-04c-capstone-prep"
author: "Pingyao Liu, Seoyoon Lee, Masha Kuritsyn"
date: "2024-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r initialization}
#
# The libraries you're going to use should go here, at the very top.
# Add tidyverse. You know you're gonna use tidyverse!
# Consider a unique random seed: set.seed(ANumberThatYouHappenToLike)
#
library(tidyverse)
library(ggplot2)
library(gtsummary)
library(dplyr)
```


```{r dataImport}
#
#read_csv()...
#data <- left_join(data, otherdata, by = matchingFeature)
#
data <- read.csv("../data/parkinsons_data.data")
glimpse(data) %>% head()
``` 


```{r dataCleaning}
#
#drop.na()...
#
data <- rename(data, subject = subject.)
sub_counts <- group_by(data, subject) %>% count(subject)
sub_counts
```
Note: graph of # of recordings, slope of the data (days vs updrs score) 
```{r}
ggplot(sub_counts, aes(x = subject, y = n)) +
  geom_point() +
  labs(title = "Scatterplot of subject vs number of recordings",
       x = "Subject",
       y = "N") +
  theme_minimal()
```

```{r, fig.width=12, fig.height=6}
ggplot(data, aes(x = test_time, y = total_UPDRS, group = subject, color = factor(subject))) +
  geom_line() +
  geom_point() +
  labs(title = "Total UPDRS Over Test Time for Each Subject",
       x = "Test Time",
       y = "Total UPDRS",
       color = "Subject") +
  scale_x_continuous(limits = c(0, 250), breaks = seq(0, 250, by = 10)) + 
  scale_y_continuous(limits = c(0, 55), breaks = seq(0, 55, by = 5)) + 
  theme_minimal()
```


The dataset has 42 subjects, with 28 males and 14 females. Each subject had a different number of recordings, with the number ranging from 101 to 168. Due to the discrepancy between the number of recordings available to each subject, we decided to <INSERT PLAN HERE>. 

We took the mean of all the metrics. 
```{r}
mean_vals <- data %>% group_by(subject) %>% summarise(across(1: PPE, .fns = mean))
mean_vals
```


## Exploratory Data Analysis

```{r}
gender_count <- group_by(data, sex, subject) %>% count(sex)
gender_count
```

